### ISSUE TITLE
Add maintainers

### ISSUE THREAD

**Issue by henryiii** [conda-forge/iminuit-feedstock#18]
You can add the scikit-hep conda-forge maintainers (me and @chrisburr) to the maintainer list, we can help keep this up to date. (@chrisburr, please verify you are okay with being added)

**Comment by chrisburr** [comment]
Aye 👍

**Comment by HDembinski** [comment]
Cool, thanks guys!

**Comment by HDembinski** [comment]
Turns out that I don't have the rights do this yet.
@mwcraig Could you please add Chris and Henry?

**Comment by chrisburr** [comment]
You can do it by editing [`recipe/meta.yml`](https://github.com/conda-forge/iminuit-feedstock/blob/master/recipe/meta.yaml#L59-L65) to add our usernames and the bot will take care of the rest.

(Normally all edits should happen through pull requests from your fork but in this case it's safe.)
