### ISSUE TITLE
Missing newer releases

### ISSUE THREAD

**Issue by henryiii** [conda-forge/iminuit-feedstock#49]
Looks like this feedstock is missing newer releases. Placeholder until I can investigate why the bot isn't picking anything up.

**Comment by henryiii** [comment]
Ahh, it was the patch that we had to inject the tests because they were missing from the SDist, I think. Probably confused the bot, since we no longer had a single source.

**Comment by chrisburr** [comment]
It's not perfect but the [status page](https://conda-forge.org/status/) normally contains a hint at the error for why the bot fails, in this case the issue was the presence of `git_url`:

```
iminuit

The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '2.3.0' to make sure they exist!

We also found the following errors:

 - migrations do not work on `git_url`s
```
