### ISSUE TITLE
re-activating support for win-32?

### ISSUE THREAD

**Issue by HDembinski** [conda-forge/iminuit-feedstock#8]
I noticed that iminuit-1.2 was also build for the win-32 platform, while iminuit-1.3.2 is only build for *-64 platforms. Should we still support win-32?

**Comment by cdeil** [comment]
Suggest to drop win 32.There's already close to no downloads at https://anaconda.org/conda-forge/iminuit/files , the number of users that want that now might be zero.

**Comment by HDembinski** [comment]
Ok, that's fine with me.
